### PR TITLE
feat: add limit search result option

### PR DESCRIPTION
**Pull request by ParthJadhav**

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Hey @TheAwiteb , I tried making it work but wasn't able to pull it off 😄 , Can you help me with it?

**Comment by TheAwiteb** [comment]
> Can you help me with it?

Sure, but after merge the PRs, to avoid a conflict that is difficult to resolve

**Comment by ParthJadhav** [comment]
Let's go. All of them are merged 🚀

**Comment by TheAwiteb** [comment]
I will create new PR, because i can't edit this

**Comment by ParthJadhav** [comment]
Okay @TheAwiteb , I'll close this one

**Pull request closed without merging**
