### PR TITLE
feat: add ability to set limit of results in output

### LINKED ISSUE #18: Possibility to set a limit for upcoming files
^ Title
---
I will work on it

### PR DESCRIPTION
**Pull request by TheAwiteb**
Fixes #18, it's work

### CODE REVIEW

**Comment by TheAwiteb** [comment]
Its not reedy yet

**Comment by TheAwiteb** [comment]
@ParthJadhav Have you seen the power of `SearchBuilder`, all this change and there is no BC 💪

**Review by ParthJadhav — APPROVED** [review]
Amazing !! Works as expected 🚀

**Comment by ParthJadhav** [comment]
> @ParthJadhav Have you seen the power of `SearchBuilder`, all this change and there is no BC 💪

True that, If it was a function there would be bc with every addition as we would had to add `NONE` even if we didn't wanted to add the argument 😄

**Comment by TheAwiteb** [comment]
@ParthJadhav Don't forget that #15 have a BC, we should release 2.0.0 and write this in the changelog

**Comment by ParthJadhav** [comment]
Oh yes!! Thanks for reminding. I was gonna release 1.1.0

**Comment by ParthJadhav** [comment]
What do you mean by "write this in changelog"

**Comment by TheAwiteb** [comment]
> What do you mean by "write this in changelog"

for example

* The `Search::new` function cannot be accessed. `SearchBuilder` must be used instead #15

**Comment by ParthJadhav** [comment]
Gotcha

**Pull request merged**
