### PR TITLE
Fix #20, search by file name

### LINKED ISSUE #20: [Bug]: Search input includes `location` to search for
```rust
let search: Vec<String> = SearchBuilder::default()
        .location("/System/")
        .search_input("Syste")
        .depth(1)
        .ignore_case()
        .build()
        .collect();
```

This will return everything contained in `/System/` directory because the Regex will be matched with the path input i.e /**Syste**m/ and return everything. 

This could be solved by adding: `.split("/").last().unwrap()` to `path`

```rust
reg_exp.is_match(&path.split("/").last().unwrap())
```

@TheAwiteb , Is there a better way to do this? Or are there any implications using this approach ?

### PR DESCRIPTION
**Pull request by TheAwiteb**
Fixes #20

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Hey @TheAwiteb , This returns only file name... We need to return the Path of the given file 😄

**Comment by TheAwiteb** [comment]
Yes, i see, how i forget this 😅

**Comment by ParthJadhav** [comment]
Haha, No worries

**Review by ParthJadhav — COMMENTED** [review]
Will this work with directories? Or only files ?

**Comment by TheAwiteb** [comment]
> Will this work with directories? Or only files ?

Both

**Comment by ParthJadhav** [comment]
Oh okay, Let me test this once and then we can merge this

**Comment by ParthJadhav** [comment]
Do you have any ideas about this one ?

https://github.com/ParthJadhav/rust_search/issues/23

I tried using .sort_by_file_name() in the walkdir builder but it doesn't work on parallel walker. And if we were to walk on single thread then it would turn out to be slow...

**Comment by ParthJadhav** [comment]
Awesome @TheAwiteb , Works as expected !! Merging this

**Comment by TheAwiteb** [comment]
> Do you have any ideas about this one ?

I'm not really good with sorting, sorry

**Review by ParthJadhav — APPROVED** [review]

**Comment by ParthJadhav** [comment]
> > Do you have any ideas about this one ?
> 
> I'm not really good with sorting, sorry

No problem, I'll investigate further

**Pull request merged**
