### PR TITLE
fix typo in example

### PR DESCRIPTION
**Pull request by SimonMonecke**

### CODE REVIEW

**Comment by ParthJadhav** [comment]
Thanks @SimonMonecke

**Review by ParthJadhav — APPROVED** [review]

**Comment by ParthJadhav** [comment]
Is it for Hacktober fest @SimonMonecke ?

**Comment by SimonMonecke** [comment]
No, I just saw your project on Reddit. And when I see typos like that, I just quickly correct them no matter what month it is :innocent:

**Comment by ParthJadhav** [comment]
That's amazing @SimonMonecke , Appreciate it 😄

**Pull request merged**
